services:
  - type: web
    name: telegram-referral-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_NAME
        sync: false
